name: space_news
description: Spark your curiosity

version: 1.2.0+2

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  ## Flutter SDK
  flutter:
    sdk: flutter

  ## Online
  cloud_firestore: ^0.12.5+1
  connectivity: ^0.4.3+2
  dio: ^2.1.7
  flutter_mailer: ^0.4.1+1
  flutter_web_browser: ^0.11.0
  webfeed: ^0.4.2  

  ## Widgets
  app_review: ^1.0.0
  add_2_calendar: ^1.3.0
  expand_widget: ^0.1.2
  flutter_local_notifications: ^0.7.1+3
  flare_flutter: ^1.5.1
  flutter_map: ^0.5.5+2
  flutter_swiper: ^1.1.6
  material_search: ^0.2.8
  native_widgets: ^0.1.1+1
  row_collection: ^0.2.1
  sliver_fab: ^1.0.0

  ## Tools
  localstorage: ^1.3.0
  provider: ^3.0.0+1
  clipboard_manager: ^0.0.4
  equatable: ^0.2.6
  flutter_i18n: ^0.6.3
  image_downloader: ^0.15.4
  location: ^2.3.5
  package_info: ^0.4.0+4
  recase: ^2.0.1
  quick_actions: ^0.3.0+2
  share: ^0.6.1+1
  shared_preferences: ^0.5.3+1
  system_setting: ^0.1.3

  ## Icons
  font_awesome_flutter: ^8.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.5.2
  json_serializable: ^3.0.0

flutter:
  fonts:
    - family: RobotoMono
      fonts:
        - asset: assets/fonts/RobotoMono-Bold.ttf
        - asset: assets/fonts/RobotoMono-Regular.ttf

    - family: ProductSans
      fonts:
        - asset: assets/fonts/ProductSans-Bold.ttf
        - asset: assets/fonts/ProductSans-Regular.ttf
        
    - family: ComicSans
      fonts:
        - asset: assets/fonts/ComicSans.ttf
  assets:
    - assets/flutter_i18n/
    - assets/animations/
    - assets/icons/android/

  uses-material-design: true
